### ISSUE TITLE
Asking

### ISSUE THREAD

**Issue by kennetpostigo** [HelpfulHuman/AxionJS#3]
Hey,

I'm opening this issue to ask if you are willing to transfer over npm ownership of this package. A couple of my friends and I are working on a frontend framework and would like to call it axion. Do you think you are willing to transfer it over?

**Comment by NickGlenn** [comment]
Sure, we actually decided to rename this project "Starship".  I will release the package today.

**Comment by kennetpostigo** [comment]
@NickGlenn thank you so much can you @ me on this thread when you do so I get a notification?

**Comment by NickGlenn** [comment]
There you go, @kennetpostigo.  I added you as a collaborator on npm.  Feel free to remove HH and myself if you wish.  Best of luck with your efforts!

**Comment by kennetpostigo** [comment]
@NickGlenn thanks a bunch!
